# general mkdocs config
site_name: DX
nav:
  - Home: index.md
  - Reference:
    - 'Formatters': reference/formatters.md
repo_url: https://github.com/noteable-io/dx
repo_name: noteable-io/dx
edit_uri: edit/main/docs/

# Material theme config
theme:
  name: readthedocs
  #name: material
  # font:
  #   text: "Lexend Deca"
  palette:
    # Toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant


# plugins
plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         options:
  #           docstring_style: 'numpy'
  # - mkdocs-jupyter:
  #     include_source: True

markdown_extensions:
  # code highlighting
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noteable_io
    - icon: fontawesome/brands/github
      link: https://github.com/noteable-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/noteable-io/
    - icon: fontawesome/brands/medium
      link: https://medium.com/noteableio
