# general mkdocs config
site_name: DX
nav:
  - Home: index.md
  # - "Plotting with DEX":
  #     - "Overview": plotting/overview.md
  #     - "Basic Charts": plotting/basic_charts.md
  # - Reference:
  #     - "Generating Data": reference/data_generation.md
  #     - "Basic Charts": reference/basic_charts.md
repo_url: https://github.com/noteable-io/dx
repo_name: noteable-io/dx
edit_uri: edit/main/docs/

# Material theme config
theme:
  name: material
  # font:
  #   text: "Lexend Deca"
  palette:
    # Toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant

# plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "numpy"
            show_root_heading: False
  - mkdocs-jupyter:
      include_source: True

markdown_extensions:
  # code highlighting
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noteable_io
    - icon: fontawesome/brands/github
      link: https://github.com/noteable-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/noteable-io/
    - icon: fontawesome/brands/medium
      link: https://medium.com/noteableio
