# general mkdocs config

# Served site information
site_name: DX
site_url: https://noteable-io.github.io/dx/
site_author: Noteable
site_description: |
  Convenient formatting and IPython display registration for tabular data and DEX media types

# Repo information
repo_url: https://github.com/noteable-io/dx
repo_name: noteable-io/dx
edit_uri: edit/main/docs

# docs root directory
docs_dir: docs

nav:
  - Home: index.md
  - Reference:
      - "Generating Data":
          - "Overview": reference/datatypes/overview.md
          - "DataFrames": reference/datatypes/dataframes.md
          - "Series":
              - "Numeric": reference/datatypes/numeric.md
              - "Text": reference/datatypes/text.md
              - "Datetime": reference/datatypes/datetime.md
              - "Geospatial/Geometry": reference/datatypes/geometry.md
              - "Misc": reference/datatypes/misc.md
          - "Checking Compatibility": reference/datatypes/compatibility.md

# Material theme config
theme:
  name: material
  # font:
  #   text: "Lexend Deca"
  palette:
    # Toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant
    - navigation.tabs
    - navigation.top

# plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "numpy"
            show_root_heading: true
  - mkdocs-jupyter:
      include_source: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: true
      caption_position: bottom

markdown_extensions:
  # code highlighting
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  # https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#options
  - pymdownx.snippets:
      base_path:
        [
          ".",
          "docs",
          "docs/screenshots",
          "docs/_charts",
          "docs/plotting",
          "docs/reference",
        ]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noteable_io
    - icon: fontawesome/brands/github
      link: https://github.com/noteable-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/noteable-io/
    - icon: fontawesome/brands/medium
      link: https://medium.com/noteableio
