###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################
extends: default

rules:
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  comments: disable

  comments-indentation: disable

  document-end: disable

  document-start:
    present: false

  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  hyphens:
    max-spaces-after: 1

  indentation:
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false

  line-length:
    max: 160

  new-line-at-end-of-file: enable

  new-lines:
    type: unix
