name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup nox
        uses: daisylb/setup-nox@v2.1.0
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: |
          poetry export -f requirements.txt --extras "docs" --without-hashes --with dev --output requirements.txt
          pip install -r requirements.txt
      - name: Install Cockroach
        uses: ./.github/actions/setup-cockroach
      - name: Install Redis
        uses: ./.github/actions/setup-redis
      - name: Install Vault
        uses: ./.github/actions/setup-vault
      - name: Run tests
        run: nox -s test-${{ matrix.python_version }}
      - name: Generate coverage XML
        run: nox -s generate_coverage_xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup nox
        uses: daisylb/setup-nox@v2.1.0
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: |
          poetry export -f requirements.txt --extras "docs" --without-hashes --with dev --output requirements.txt
          pip install -r requirements.txt
      - name: Run lint
        run: nox -s lint
